// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: seckill.proto

package product_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrontSecKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Pagesize      int64                  `protobuf:"varint,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontSecKillRequest) Reset() {
	*x = FrontSecKillRequest{}
	mi := &file_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontSecKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontSecKillRequest) ProtoMessage() {}

func (x *FrontSecKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontSecKillRequest.ProtoReflect.Descriptor instead.
func (*FrontSecKillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *FrontSecKillRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FrontSecKillRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

type FrongSecKillDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Seckill       *SecKill               `protobuf:"bytes,3,opt,name=seckill,proto3" json:"seckill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrongSecKillDetailResponse) Reset() {
	*x = FrongSecKillDetailResponse{}
	mi := &file_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrongSecKillDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrongSecKillDetailResponse) ProtoMessage() {}

func (x *FrongSecKillDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrongSecKillDetailResponse.ProtoReflect.Descriptor instead.
func (*FrongSecKillDetailResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *FrongSecKillDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FrongSecKillDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FrongSecKillDetailResponse) GetSeckill() *SecKill {
	if x != nil {
		return x.Seckill
	}
	return nil
}

type FrontSecKillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	SeckillList   []*SecKill             `protobuf:"bytes,3,rep,name=seckill_list,json=seckillList,proto3" json:"seckill_list,omitempty"`
	Current       int64                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPage     int64                  `protobuf:"varint,6,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontSecKillResponse) Reset() {
	*x = FrontSecKillResponse{}
	mi := &file_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontSecKillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontSecKillResponse) ProtoMessage() {}

func (x *FrontSecKillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontSecKillResponse.ProtoReflect.Descriptor instead.
func (*FrontSecKillResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *FrontSecKillResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FrontSecKillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FrontSecKillResponse) GetSeckillList() []*SecKill {
	if x != nil {
		return x.SeckillList
	}
	return nil
}

func (x *FrontSecKillResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *FrontSecKillResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FrontSecKillResponse) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type SecKillToEditResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Seckill       *SecKill                 `protobuf:"bytes,3,opt,name=seckill,proto3" json:"seckill,omitempty"`
	ProductsNo    []*SecKillProductRequest `protobuf:"bytes,4,rep,name=products_no,json=productsNo,proto3" json:"products_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillToEditResponse) Reset() {
	*x = SecKillToEditResponse{}
	mi := &file_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillToEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillToEditResponse) ProtoMessage() {}

func (x *SecKillToEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillToEditResponse.ProtoReflect.Descriptor instead.
func (*SecKillToEditResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *SecKillToEditResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillToEditResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SecKillToEditResponse) GetSeckill() *SecKill {
	if x != nil {
		return x.Seckill
	}
	return nil
}

func (x *SecKillToEditResponse) GetProductsNo() []*SecKillProductRequest {
	if x != nil {
		return x.ProductsNo
	}
	return nil
}

type SecKillDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillDelRequest) Reset() {
	*x = SecKillDelRequest{}
	mi := &file_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillDelRequest) ProtoMessage() {}

func (x *SecKillDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillDelRequest.ProtoReflect.Descriptor instead.
func (*SecKillDelRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *SecKillDelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SecKillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillResponse) Reset() {
	*x = SecKillResponse{}
	mi := &file_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillResponse) ProtoMessage() {}

func (x *SecKillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillResponse.ProtoReflect.Descriptor instead.
func (*SecKillResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *SecKillResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_seckill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{6}
}

type ProductResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Products      []*SecKillProductRequest `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_seckill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{7}
}

func (x *ProductResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ProductResponse) GetProducts() []*SecKillProductRequest {
	if x != nil {
		return x.Products
	}
	return nil
}

type SecKillProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pname         string                 `protobuf:"bytes,2,opt,name=pname,proto3" json:"pname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillProductRequest) Reset() {
	*x = SecKillProductRequest{}
	mi := &file_seckill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillProductRequest) ProtoMessage() {}

func (x *SecKillProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillProductRequest.ProtoReflect.Descriptor instead.
func (*SecKillProductRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{8}
}

func (x *SecKillProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SecKillProductRequest) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

type SecKillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Pagesize      int64                  `protobuf:"varint,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillsRequest) Reset() {
	*x = SecKillsRequest{}
	mi := &file_seckill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillsRequest) ProtoMessage() {}

func (x *SecKillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillsRequest.ProtoReflect.Descriptor instead.
func (*SecKillsRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{9}
}

func (x *SecKillsRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *SecKillsRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

type SecKillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Seckills      []*SecKill             `protobuf:"bytes,3,rep,name=seckills,proto3" json:"seckills,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Current       int64                  `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKillsResponse) Reset() {
	*x = SecKillsResponse{}
	mi := &file_seckill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillsResponse) ProtoMessage() {}

func (x *SecKillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillsResponse.ProtoReflect.Descriptor instead.
func (*SecKillsResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{10}
}

func (x *SecKillsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SecKillsResponse) GetSeckills() []*SecKill {
	if x != nil {
		return x.Seckills
	}
	return nil
}

func (x *SecKillsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SecKillsResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *SecKillsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SecKill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Pid           int64                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Pname         string                 `protobuf:"bytes,6,opt,name=pname,proto3" json:"pname,omitempty"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreateTime    string                 `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Pic           string                 `protobuf:"bytes,10,opt,name=pic,proto3" json:"pic,omitempty"`
	PPrice        float32                `protobuf:"fixed32,11,opt,name=p_price,json=pPrice,proto3" json:"p_price,omitempty"`
	Pdesc         string                 `protobuf:"bytes,12,opt,name=pdesc,proto3" json:"pdesc,omitempty"`
	Unit          string                 `protobuf:"bytes,13,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecKill) Reset() {
	*x = SecKill{}
	mi := &file_seckill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKill) ProtoMessage() {}

func (x *SecKill) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKill.ProtoReflect.Descriptor instead.
func (*SecKill) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{11}
}

func (x *SecKill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SecKill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecKill) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SecKill) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SecKill) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SecKill) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *SecKill) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SecKill) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SecKill) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SecKill) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SecKill) GetPPrice() float32 {
	if x != nil {
		return x.PPrice
	}
	return 0
}

func (x *SecKill) GetPdesc() string {
	if x != nil {
		return x.Pdesc
	}
	return ""
}

func (x *SecKill) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_seckill_proto protoreflect.FileDescriptor

const file_seckill_proto_rawDesc = "" +
	"\n" +
	"\rseckill.proto\x12\vproduct_srv\"T\n" +
	"\x13FrontSecKillRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x1a\n" +
	"\bpagesize\x18\x02 \x01(\x03R\bpagesize\"r\n" +
	"\x1aFrongSecKillDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\aseckill\x18\x03 \x01(\v2\x14.product_srv.SecKillR\aseckill\"\xcb\x01\n" +
	"\x14FrontSecKillResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x127\n" +
	"\fseckill_list\x18\x03 \x03(\v2\x14.product_srv.SecKillR\vseckillList\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x03R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"total_page\x18\x06 \x01(\x03R\ttotalPage\"\xb2\x01\n" +
	"\x15SecKillToEditResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\aseckill\x18\x03 \x01(\v2\x14.product_srv.SecKillR\aseckill\x12C\n" +
	"\vproducts_no\x18\x04 \x03(\v2\".product_srv.SecKillProductRequestR\n" +
	"productsNo\"#\n" +
	"\x11SecKillDelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x0fSecKillResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x10\n" +
	"\x0eProductRequest\"w\n" +
	"\x0fProductResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12>\n" +
	"\bproducts\x18\x03 \x03(\v2\".product_srv.SecKillProductRequestR\bproducts\"=\n" +
	"\x15SecKillProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05pname\x18\x02 \x01(\tR\x05pname\"P\n" +
	"\x0fSecKillsRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x1a\n" +
	"\bpagesize\x18\x02 \x01(\x03R\bpagesize\"\xb7\x01\n" +
	"\x10SecKillsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\bseckills\x18\x03 \x03(\v2\x14.product_srv.SecKillR\bseckills\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x18\n" +
	"\acurrent\x18\x05 \x01(\x03R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"\xad\x02\n" +
	"\aSecKill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x03R\x03pid\x12\x14\n" +
	"\x05pname\x18\x06 \x01(\tR\x05pname\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\tR\n" +
	"createTime\x12\x10\n" +
	"\x03pic\x18\n" +
	" \x01(\tR\x03pic\x12\x17\n" +
	"\ap_price\x18\v \x01(\x02R\x06pPrice\x12\x14\n" +
	"\x05pdesc\x18\f \x01(\tR\x05pdesc\x12\x12\n" +
	"\x04unit\x18\r \x01(\tR\x04unit2\x90\x05\n" +
	"\bSecKills\x12L\n" +
	"\vSecKillList\x12\x1c.product_srv.SecKillsRequest\x1a\x1d.product_srv.SecKillsResponse\"\x00\x12J\n" +
	"\vGetProducts\x12\x1b.product_srv.ProductRequest\x1a\x1c.product_srv.ProductResponse\"\x00\x12B\n" +
	"\n" +
	"SecKillAdd\x12\x14.product_srv.SecKill\x1a\x1c.product_srv.SecKillResponse\"\x00\x12L\n" +
	"\n" +
	"SecKillDel\x12\x1e.product_srv.SecKillDelRequest\x1a\x1c.product_srv.SecKillResponse\"\x00\x12U\n" +
	"\rSecKillToEdit\x12\x1e.product_srv.SecKillDelRequest\x1a\".product_srv.SecKillToEditResponse\"\x00\x12E\n" +
	"\rSecKillDoEdit\x12\x14.product_srv.SecKill\x1a\x1c.product_srv.SecKillResponse\"\x00\x12Y\n" +
	"\x10FrontSecKillList\x12 .product_srv.FrontSecKillRequest\x1a!.product_srv.FrontSecKillResponse\"\x00\x12_\n" +
	"\x12FrontSecKillDetail\x12\x1e.product_srv.SecKillDelRequest\x1a'.product_srv.FrongSecKillDetailResponse\"\x00B\x10Z\x0e./;product_srvb\x06proto3"

var (
	file_seckill_proto_rawDescOnce sync.Once
	file_seckill_proto_rawDescData []byte
)

func file_seckill_proto_rawDescGZIP() []byte {
	file_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)))
	})
	return file_seckill_proto_rawDescData
}

var file_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_seckill_proto_goTypes = []any{
	(*FrontSecKillRequest)(nil),        // 0: product_srv.FrontSecKillRequest
	(*FrongSecKillDetailResponse)(nil), // 1: product_srv.FrongSecKillDetailResponse
	(*FrontSecKillResponse)(nil),       // 2: product_srv.FrontSecKillResponse
	(*SecKillToEditResponse)(nil),      // 3: product_srv.SecKillToEditResponse
	(*SecKillDelRequest)(nil),          // 4: product_srv.SecKillDelRequest
	(*SecKillResponse)(nil),            // 5: product_srv.SecKillResponse
	(*ProductRequest)(nil),             // 6: product_srv.ProductRequest
	(*ProductResponse)(nil),            // 7: product_srv.ProductResponse
	(*SecKillProductRequest)(nil),      // 8: product_srv.SecKillProductRequest
	(*SecKillsRequest)(nil),            // 9: product_srv.SecKillsRequest
	(*SecKillsResponse)(nil),           // 10: product_srv.SecKillsResponse
	(*SecKill)(nil),                    // 11: product_srv.SecKill
}
var file_seckill_proto_depIdxs = []int32{
	11, // 0: product_srv.FrongSecKillDetailResponse.seckill:type_name -> product_srv.SecKill
	11, // 1: product_srv.FrontSecKillResponse.seckill_list:type_name -> product_srv.SecKill
	11, // 2: product_srv.SecKillToEditResponse.seckill:type_name -> product_srv.SecKill
	8,  // 3: product_srv.SecKillToEditResponse.products_no:type_name -> product_srv.SecKillProductRequest
	8,  // 4: product_srv.ProductResponse.products:type_name -> product_srv.SecKillProductRequest
	11, // 5: product_srv.SecKillsResponse.seckills:type_name -> product_srv.SecKill
	9,  // 6: product_srv.SecKills.SecKillList:input_type -> product_srv.SecKillsRequest
	6,  // 7: product_srv.SecKills.GetProducts:input_type -> product_srv.ProductRequest
	11, // 8: product_srv.SecKills.SecKillAdd:input_type -> product_srv.SecKill
	4,  // 9: product_srv.SecKills.SecKillDel:input_type -> product_srv.SecKillDelRequest
	4,  // 10: product_srv.SecKills.SecKillToEdit:input_type -> product_srv.SecKillDelRequest
	11, // 11: product_srv.SecKills.SecKillDoEdit:input_type -> product_srv.SecKill
	0,  // 12: product_srv.SecKills.FrontSecKillList:input_type -> product_srv.FrontSecKillRequest
	4,  // 13: product_srv.SecKills.FrontSecKillDetail:input_type -> product_srv.SecKillDelRequest
	10, // 14: product_srv.SecKills.SecKillList:output_type -> product_srv.SecKillsResponse
	7,  // 15: product_srv.SecKills.GetProducts:output_type -> product_srv.ProductResponse
	5,  // 16: product_srv.SecKills.SecKillAdd:output_type -> product_srv.SecKillResponse
	5,  // 17: product_srv.SecKills.SecKillDel:output_type -> product_srv.SecKillResponse
	3,  // 18: product_srv.SecKills.SecKillToEdit:output_type -> product_srv.SecKillToEditResponse
	5,  // 19: product_srv.SecKills.SecKillDoEdit:output_type -> product_srv.SecKillResponse
	2,  // 20: product_srv.SecKills.FrontSecKillList:output_type -> product_srv.FrontSecKillResponse
	1,  // 21: product_srv.SecKills.FrontSecKillDetail:output_type -> product_srv.FrongSecKillDetailResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_seckill_proto_init() }
func file_seckill_proto_init() {
	if File_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_proto_msgTypes,
	}.Build()
	File_seckill_proto = out.File
	file_seckill_proto_goTypes = nil
	file_seckill_proto_depIdxs = nil
}
