// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/seckill_srv.proto

package seckill_srv

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Zhiliaoseckillsrv service

func NewZhiliaoseckillsrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Zhiliaoseckillsrv service

type ZhiliaoseckillsrvService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Zhiliaoseckillsrv_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Zhiliaoseckillsrv_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Zhiliaoseckillsrv_BidiStreamService, error)
}

type zhiliaoseckillsrvService struct {
	c    client.Client
	name string
}

func NewZhiliaoseckillsrvService(name string, c client.Client) ZhiliaoseckillsrvService {
	return &zhiliaoseckillsrvService{
		c:    c,
		name: name,
	}
}

func (c *zhiliaoseckillsrvService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Zhiliaoseckillsrv.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zhiliaoseckillsrvService) ClientStream(ctx context.Context, opts ...client.CallOption) (Zhiliaoseckillsrv_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Zhiliaoseckillsrv.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &zhiliaoseckillsrvServiceClientStream{stream}, nil
}

type Zhiliaoseckillsrv_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type zhiliaoseckillsrvServiceClientStream struct {
	stream client.Stream
}

func (x *zhiliaoseckillsrvServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *zhiliaoseckillsrvServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *zhiliaoseckillsrvService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Zhiliaoseckillsrv_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Zhiliaoseckillsrv.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &zhiliaoseckillsrvServiceServerStream{stream}, nil
}

type Zhiliaoseckillsrv_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type zhiliaoseckillsrvServiceServerStream struct {
	stream client.Stream
}

func (x *zhiliaoseckillsrvServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *zhiliaoseckillsrvServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zhiliaoseckillsrvService) BidiStream(ctx context.Context, opts ...client.CallOption) (Zhiliaoseckillsrv_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Zhiliaoseckillsrv.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &zhiliaoseckillsrvServiceBidiStream{stream}, nil
}

type Zhiliaoseckillsrv_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type zhiliaoseckillsrvServiceBidiStream struct {
	stream client.Stream
}

func (x *zhiliaoseckillsrvServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *zhiliaoseckillsrvServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Zhiliaoseckillsrv service

type ZhiliaoseckillsrvHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Zhiliaoseckillsrv_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Zhiliaoseckillsrv_ServerStreamStream) error
	BidiStream(context.Context, Zhiliaoseckillsrv_BidiStreamStream) error
}

func RegisterZhiliaoseckillsrvHandler(s server.Server, hdlr ZhiliaoseckillsrvHandler, opts ...server.HandlerOption) error {
	type zhiliaoseckillsrv interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Zhiliaoseckillsrv struct {
		zhiliaoseckillsrv
	}
	h := &zhiliaoseckillsrvHandler{hdlr}
	return s.Handle(s.NewHandler(&Zhiliaoseckillsrv{h}, opts...))
}

type zhiliaoseckillsrvHandler struct {
	ZhiliaoseckillsrvHandler
}

func (h *zhiliaoseckillsrvHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ZhiliaoseckillsrvHandler.Call(ctx, in, out)
}

func (h *zhiliaoseckillsrvHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ZhiliaoseckillsrvHandler.ClientStream(ctx, &zhiliaoseckillsrvClientStreamStream{stream})
}

type Zhiliaoseckillsrv_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type zhiliaoseckillsrvClientStreamStream struct {
	stream server.Stream
}

func (x *zhiliaoseckillsrvClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *zhiliaoseckillsrvHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ZhiliaoseckillsrvHandler.ServerStream(ctx, m, &zhiliaoseckillsrvServerStreamStream{stream})
}

type Zhiliaoseckillsrv_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type zhiliaoseckillsrvServerStreamStream struct {
	stream server.Stream
}

func (x *zhiliaoseckillsrvServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *zhiliaoseckillsrvHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ZhiliaoseckillsrvHandler.BidiStream(ctx, &zhiliaoseckillsrvBidiStreamStream{stream})
}

type Zhiliaoseckillsrv_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type zhiliaoseckillsrvBidiStreamStream struct {
	stream server.Stream
}

func (x *zhiliaoseckillsrvBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *zhiliaoseckillsrvBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *zhiliaoseckillsrvBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *zhiliaoseckillsrvBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *zhiliaoseckillsrvBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
