// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: product.proto

package product_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Pic           string                 `protobuf:"bytes,6,opt,name=pic,proto3" json:"pic,omitempty"`
	Desc          string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Product) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Product) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Product) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Pagesize      int64                  `protobuf:"varint,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsRequest) Reset() {
	*x = ProductsRequest{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsRequest) ProtoMessage() {}

func (x *ProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsRequest.ProtoReflect.Descriptor instead.
func (*ProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductsRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ProductsRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

type ProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Products      []*Product             `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Current       int64                  `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsResponse) Reset() {
	*x = ProductsResponse{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResponse) ProtoMessage() {}

func (x *ProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResponse.ProtoReflect.Descriptor instead.
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProductsResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ProductsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProductAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Pic           string                 `protobuf:"bytes,5,opt,name=pic,proto3" json:"pic,omitempty"`
	Desc          string                 `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime    string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAddRequest) Reset() {
	*x = ProductAddRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAddRequest) ProtoMessage() {}

func (x *ProductAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAddRequest.ProtoReflect.Descriptor instead.
func (*ProductAddRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAddRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductAddRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ProductAddRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductAddRequest) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *ProductAddRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProductAddRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ProductAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAddResponse) Reset() {
	*x = ProductAddResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAddResponse) ProtoMessage() {}

func (x *ProductAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAddResponse.ProtoReflect.Descriptor instead.
func (*ProductAddResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductAddResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductAddResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ProductEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Pic           string                 `protobuf:"bytes,6,opt,name=pic,proto3" json:"pic,omitempty"`
	Desc          string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductEditRequest) Reset() {
	*x = ProductEditRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEditRequest) ProtoMessage() {}

func (x *ProductEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEditRequest.ProtoReflect.Descriptor instead.
func (*ProductEditRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductEditRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductEditRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductEditRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ProductEditRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductEditRequest) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *ProductEditRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProductEditRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ProductEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductEditResponse) Reset() {
	*x = ProductEditResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEditResponse) ProtoMessage() {}

func (x *ProductEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEditResponse.ProtoReflect.Descriptor instead.
func (*ProductEditResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductEditResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductEditResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ProductDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDelRequest) Reset() {
	*x = ProductDelRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDelRequest) ProtoMessage() {}

func (x *ProductDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDelRequest.ProtoReflect.Descriptor instead.
func (*ProductDelRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductDelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDelResponse) Reset() {
	*x = ProductDelResponse{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDelResponse) ProtoMessage() {}

func (x *ProductDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDelResponse.ProtoReflect.Descriptor instead.
func (*ProductDelResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *ProductDelResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductDelResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ProductToEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductToEditRequest) Reset() {
	*x = ProductToEditRequest{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductToEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductToEditRequest) ProtoMessage() {}

func (x *ProductToEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductToEditRequest.ProtoReflect.Descriptor instead.
func (*ProductToEditRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductToEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductToEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Product       *Product               `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductToEditResponse) Reset() {
	*x = ProductToEditResponse{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductToEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductToEditResponse) ProtoMessage() {}

func (x *ProductToEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductToEditResponse.ProtoReflect.Descriptor instead.
func (*ProductToEditResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *ProductToEditResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProductToEditResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ProductToEditResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\vproduct_srv\"\xb0\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x10\n" +
	"\x03pic\x18\x06 \x01(\tR\x03pic\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\"P\n" +
	"\x0fProductsRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x1a\n" +
	"\bpagesize\x18\x02 \x01(\x03R\bpagesize\"\xb7\x01\n" +
	"\x10ProductsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\bproducts\x18\x03 \x03(\v2\x14.product_srv.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x18\n" +
	"\acurrent\x18\x05 \x01(\x03R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"\xaa\x01\n" +
	"\x11ProductAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x10\n" +
	"\x03pic\x18\x05 \x01(\tR\x03pic\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime\":\n" +
	"\x12ProductAddResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xbb\x01\n" +
	"\x12ProductEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x10\n" +
	"\x03pic\x18\x06 \x01(\tR\x03pic\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\";\n" +
	"\x13ProductEditResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"#\n" +
	"\x11ProductDelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x12ProductDelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"&\n" +
	"\x14ProductToEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"m\n" +
	"\x15ProductToEditResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\aproduct\x18\x03 \x01(\v2\x14.product_srv.ProductR\aproduct2\xab\x03\n" +
	"\bProducts\x12M\n" +
	"\fProductsList\x12\x1c.product_srv.ProductsRequest\x1a\x1d.product_srv.ProductsResponse\"\x00\x12O\n" +
	"\n" +
	"ProductAdd\x12\x1e.product_srv.ProductAddRequest\x1a\x1f.product_srv.ProductAddResponse\"\x00\x12O\n" +
	"\n" +
	"ProductDel\x12\x1e.product_srv.ProductDelRequest\x1a\x1f.product_srv.ProductDelResponse\"\x00\x12X\n" +
	"\rProductToEdit\x12!.product_srv.ProductToEditRequest\x1a\".product_srv.ProductToEditResponse\"\x00\x12T\n" +
	"\rProductDoEdit\x12\x1f.product_srv.ProductEditRequest\x1a .product_srv.ProductEditResponse\"\x00B\x10Z\x0e./;product_srvb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_proto_goTypes = []any{
	(*Product)(nil),               // 0: product_srv.Product
	(*ProductsRequest)(nil),       // 1: product_srv.ProductsRequest
	(*ProductsResponse)(nil),      // 2: product_srv.ProductsResponse
	(*ProductAddRequest)(nil),     // 3: product_srv.ProductAddRequest
	(*ProductAddResponse)(nil),    // 4: product_srv.ProductAddResponse
	(*ProductEditRequest)(nil),    // 5: product_srv.ProductEditRequest
	(*ProductEditResponse)(nil),   // 6: product_srv.ProductEditResponse
	(*ProductDelRequest)(nil),     // 7: product_srv.ProductDelRequest
	(*ProductDelResponse)(nil),    // 8: product_srv.ProductDelResponse
	(*ProductToEditRequest)(nil),  // 9: product_srv.ProductToEditRequest
	(*ProductToEditResponse)(nil), // 10: product_srv.ProductToEditResponse
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: product_srv.ProductsResponse.products:type_name -> product_srv.Product
	0,  // 1: product_srv.ProductToEditResponse.product:type_name -> product_srv.Product
	1,  // 2: product_srv.Products.ProductsList:input_type -> product_srv.ProductsRequest
	3,  // 3: product_srv.Products.ProductAdd:input_type -> product_srv.ProductAddRequest
	7,  // 4: product_srv.Products.ProductDel:input_type -> product_srv.ProductDelRequest
	9,  // 5: product_srv.Products.ProductToEdit:input_type -> product_srv.ProductToEditRequest
	5,  // 6: product_srv.Products.ProductDoEdit:input_type -> product_srv.ProductEditRequest
	2,  // 7: product_srv.Products.ProductsList:output_type -> product_srv.ProductsResponse
	4,  // 8: product_srv.Products.ProductAdd:output_type -> product_srv.ProductAddResponse
	8,  // 9: product_srv.Products.ProductDel:output_type -> product_srv.ProductDelResponse
	10, // 10: product_srv.Products.ProductToEdit:output_type -> product_srv.ProductToEditResponse
	6,  // 11: product_srv.Products.ProductDoEdit:output_type -> product_srv.ProductEditResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
