// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: proto/front_user/front_user.proto

package front_user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrontUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Reassword     string                 `protobuf:"bytes,4,opt,name=reassword,proto3" json:"reassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUserRequest) Reset() {
	*x = FrontUserRequest{}
	mi := &file_proto_front_user_front_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUserRequest) ProtoMessage() {}

func (x *FrontUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_front_user_front_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUserRequest.ProtoReflect.Descriptor instead.
func (*FrontUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_front_user_front_user_proto_rawDescGZIP(), []int{0}
}

func (x *FrontUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FrontUserRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FrontUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *FrontUserRequest) GetReassword() string {
	if x != nil {
		return x.Reassword
	}
	return ""
}

type FrontUserMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUserMailRequest) Reset() {
	*x = FrontUserMailRequest{}
	mi := &file_proto_front_user_front_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUserMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUserMailRequest) ProtoMessage() {}

func (x *FrontUserMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_front_user_front_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUserMailRequest.ProtoReflect.Descriptor instead.
func (*FrontUserMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_front_user_front_user_proto_rawDescGZIP(), []int{1}
}

func (x *FrontUserMailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FrontUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUserResponse) Reset() {
	*x = FrontUserResponse{}
	mi := &file_proto_front_user_front_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUserResponse) ProtoMessage() {}

func (x *FrontUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_front_user_front_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUserResponse.ProtoReflect.Descriptor instead.
func (*FrontUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_front_user_front_user_proto_rawDescGZIP(), []int{2}
}

func (x *FrontUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FrontUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FrontUserResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_proto_front_user_front_user_proto protoreflect.FileDescriptor

const file_proto_front_user_front_user_proto_rawDesc = "" +
	"\n" +
	"!proto/front_user/front_user.proto\x12\buser_srv\"v\n" +
	"\x10FrontUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1c\n" +
	"\treassword\x18\x04 \x01(\tR\treassword\",\n" +
	"\x14FrontUserMailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"V\n" +
	"\x11FrontUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName2\xfd\x01\n" +
	"\tFrontUser\x12N\n" +
	"\x11FrontUserRegister\x12\x1a.user_srv.FrontUserRequest\x1a\x1b.user_srv.FrontUserResponse\"\x00\x12S\n" +
	"\x12FrontUserSendEmail\x12\x1e.user_srv.FrontUserMailRequest\x1a\x1b.user_srv.FrontUserResponse\"\x00\x12K\n" +
	"\x0eFrontUserLogin\x12\x1a.user_srv.FrontUserRequest\x1a\x1b.user_srv.FrontUserResponse\"\x00B\rZ\v./;user_srvb\x06proto3"

var (
	file_proto_front_user_front_user_proto_rawDescOnce sync.Once
	file_proto_front_user_front_user_proto_rawDescData []byte
)

func file_proto_front_user_front_user_proto_rawDescGZIP() []byte {
	file_proto_front_user_front_user_proto_rawDescOnce.Do(func() {
		file_proto_front_user_front_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_front_user_front_user_proto_rawDesc), len(file_proto_front_user_front_user_proto_rawDesc)))
	})
	return file_proto_front_user_front_user_proto_rawDescData
}

var file_proto_front_user_front_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_front_user_front_user_proto_goTypes = []any{
	(*FrontUserRequest)(nil),     // 0: user_srv.FrontUserRequest
	(*FrontUserMailRequest)(nil), // 1: user_srv.FrontUserMailRequest
	(*FrontUserResponse)(nil),    // 2: user_srv.FrontUserResponse
}
var file_proto_front_user_front_user_proto_depIdxs = []int32{
	0, // 0: user_srv.FrontUser.FrontUserRegister:input_type -> user_srv.FrontUserRequest
	1, // 1: user_srv.FrontUser.FrontUserSendEmail:input_type -> user_srv.FrontUserMailRequest
	0, // 2: user_srv.FrontUser.FrontUserLogin:input_type -> user_srv.FrontUserRequest
	2, // 3: user_srv.FrontUser.FrontUserRegister:output_type -> user_srv.FrontUserResponse
	2, // 4: user_srv.FrontUser.FrontUserSendEmail:output_type -> user_srv.FrontUserResponse
	2, // 5: user_srv.FrontUser.FrontUserLogin:output_type -> user_srv.FrontUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_front_user_front_user_proto_init() }
func file_proto_front_user_front_user_proto_init() {
	if File_proto_front_user_front_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_front_user_front_user_proto_rawDesc), len(file_proto_front_user_front_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_front_user_front_user_proto_goTypes,
		DependencyIndexes: file_proto_front_user_front_user_proto_depIdxs,
		MessageInfos:      file_proto_front_user_front_user_proto_msgTypes,
	}.Build()
	File_proto_front_user_front_user_proto = out.File
	file_proto_front_user_front_user_proto_goTypes = nil
	file_proto_front_user_front_user_proto_depIdxs = nil
}
