// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: admin_user.proto

package user_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrontUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Pagesize      int64                  `protobuf:"varint,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUsersRequest) Reset() {
	*x = FrontUsersRequest{}
	mi := &file_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUsersRequest) ProtoMessage() {}

func (x *FrontUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUsersRequest.ProtoReflect.Descriptor instead.
func (*FrontUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *FrontUsersRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FrontUsersRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

type FrontUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FrontUsers    []*FrontUserMessage    `protobuf:"bytes,3,rep,name=front_users,json=frontUsers,proto3" json:"front_users,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Current       int64                  `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUsersResponse) Reset() {
	*x = FrontUsersResponse{}
	mi := &file_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUsersResponse) ProtoMessage() {}

func (x *FrontUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUsersResponse.ProtoReflect.Descriptor instead.
func (*FrontUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *FrontUsersResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FrontUsersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FrontUsersResponse) GetFrontUsers() []*FrontUserMessage {
	if x != nil {
		return x.FrontUsers
	}
	return nil
}

func (x *FrontUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FrontUsersResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *FrontUsersResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FrontUserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontUserMessage) Reset() {
	*x = FrontUserMessage{}
	mi := &file_admin_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontUserMessage) ProtoMessage() {}

func (x *FrontUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontUserMessage.ProtoReflect.Descriptor instead.
func (*FrontUserMessage) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{2}
}

func (x *FrontUserMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FrontUserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FrontUserMessage) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *FrontUserMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FrontUserMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type AdminUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserRequest) Reset() {
	*x = AdminUserRequest{}
	mi := &file_admin_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserRequest) ProtoMessage() {}

func (x *AdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserRequest.ProtoReflect.Descriptor instead.
func (*AdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserResponse) Reset() {
	*x = AdminUserResponse{}
	mi := &file_admin_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserResponse) ProtoMessage() {}

func (x *AdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserResponse.ProtoReflect.Descriptor instead.
func (*AdminUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{4}
}

func (x *AdminUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AdminUserResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_admin_user_proto protoreflect.FileDescriptor

const file_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x10admin_user.proto\x12\buser_srv\"R\n" +
	"\x11FrontUsersRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x1a\n" +
	"\bpagesize\x18\x02 \x01(\x03R\bpagesize\"\xc4\x01\n" +
	"\x12FrontUsersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12;\n" +
	"\vfront_users\x18\x03 \x03(\v2\x1a.user_srv.FrontUserMessageR\n" +
	"frontUsers\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x18\n" +
	"\acurrent\x18\x05 \x01(\x03R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"\x85\x01\n" +
	"\x10FrontUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\"J\n" +
	"\x10AdminUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"V\n" +
	"\x11AdminUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName2\xa6\x01\n" +
	"\tAdminUser\x12K\n" +
	"\x0eAdminUserLogin\x12\x1a.user_srv.AdminUserRequest\x1a\x1b.user_srv.AdminUserResponse\"\x00\x12L\n" +
	"\rFrontUserList\x12\x1b.user_srv.FrontUsersRequest\x1a\x1c.user_srv.FrontUsersResponse\"\x00B\rZ\v./;user_srvb\x06proto3"

var (
	file_admin_user_proto_rawDescOnce sync.Once
	file_admin_user_proto_rawDescData []byte
)

func file_admin_user_proto_rawDescGZIP() []byte {
	file_admin_user_proto_rawDescOnce.Do(func() {
		file_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_user_proto_rawDesc), len(file_admin_user_proto_rawDesc)))
	})
	return file_admin_user_proto_rawDescData
}

var file_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_user_proto_goTypes = []any{
	(*FrontUsersRequest)(nil),  // 0: user_srv.FrontUsersRequest
	(*FrontUsersResponse)(nil), // 1: user_srv.FrontUsersResponse
	(*FrontUserMessage)(nil),   // 2: user_srv.FrontUserMessage
	(*AdminUserRequest)(nil),   // 3: user_srv.AdminUserRequest
	(*AdminUserResponse)(nil),  // 4: user_srv.AdminUserResponse
}
var file_admin_user_proto_depIdxs = []int32{
	2, // 0: user_srv.FrontUsersResponse.front_users:type_name -> user_srv.FrontUserMessage
	3, // 1: user_srv.AdminUser.AdminUserLogin:input_type -> user_srv.AdminUserRequest
	0, // 2: user_srv.AdminUser.FrontUserList:input_type -> user_srv.FrontUsersRequest
	4, // 3: user_srv.AdminUser.AdminUserLogin:output_type -> user_srv.AdminUserResponse
	1, // 4: user_srv.AdminUser.FrontUserList:output_type -> user_srv.FrontUsersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_user_proto_init() }
func file_admin_user_proto_init() {
	if File_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_user_proto_rawDesc), len(file_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_user_proto_goTypes,
		DependencyIndexes: file_admin_user_proto_depIdxs,
		MessageInfos:      file_admin_user_proto_msgTypes,
	}.Build()
	File_admin_user_proto = out.File
	file_admin_user_proto_goTypes = nil
	file_admin_user_proto_depIdxs = nil
}
